#!/bin/bash

nb_concurrent_processes=28
j=0
while read LINE; do
  i=$[i + 1]
  echo -n "$LINE:" >> OUT4.$i &
  curl --proxy 127.0.0.1:5557 --connect-timeout 70 --max-time 70 -s -o /dev/null -w "%{http_code}\n" "$LINE" >> OUT4.$i &
  ((++j == nb_concurrent_processes)) && { j=0; wait; }
done < xad
